apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quickring
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: website
  owner: dlockamy@gmail.com
  lifecycle: experimental
